version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:

  $SERVICENAME:
    image: $IMAGENAME
    labels:
      - traefik.http.routers.$SERVICENAME.rule=Host(`$DOMAINNAME`)
      - traefik.http.routers.$SERVICENAME.tls=true
      - traefik.http.routers.$SERVICENAME.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
